### ISSUE TITLE
headerType() '*' logic is incorrect.

### ISSUE THREAD

**Issue by Qix-** [hapijs/accept#34]
https://github.com/hapijs/accept/blob/master/lib/mediatype.js#L41-L45

Given the above logic, the following line incorrectly returns `text/plain`. It should favor `image/*` mimetypes over `text/plain`.

```javascript
accept.mediaType('text/plain;q=0.1, image/*;q=1', ['text/plain', 'image/jpeg'])
```

**Comment by Qix-** [comment]
In fact, the whole `mediaType()` implementation seems to ignore everything that makes that method useful... it doesn't even parse the header, just does naïve string checks.

**Comment by sholladay** [comment]
Isn't this expected? The documentation on the `preferences` array isn't super clear/detailed about the exact semantics in cases like this, but my understanding is that the `preferences` array takes precedence over the header's Q weightings. So `text/plain` is being returned because that's the first item in your `preferences` array that matches the allowed types in the header. If you reverse the order of your `preferences` array, then it will return `image/jpeg`. And if you omit the `preferences` array (or leave it empty), then `image/*` will be returned, as expected from the Q weightings.

Seems to me like we need a way to specify whether precedence is given to the server or client. It just assumes the former right now.

**Comment by Qix-** [comment]
I want to give precedence to the client. If server got precedence, then all Id need are a list of Mime's without q values. That way I could make a selection myself.

**Comment by hueniverse** [comment]
The way * is looked up it wrong. It lacks context in the header.

**Comment by hueniverse** [comment]
Marked as breaking because the results will change for some headers, but released as minor since the new results are still correct according to the spec. This gives alphabetical preference over header position but only for values that have the same q.
